name: simurex
channels:
  - conda-forge
dependencies:
  - python>=3.5
  - jupyter
  - numpy
  - pandas
  - holoviews
  - bokeh
  - xarray
  - scikit-learn
  - seaborn
  - pytables
  - statsmodel
  - pip:
    - salib
