name: simurex
channels:
  - conda-forge
dependencies:
  - python=3.6
  - jupyter
  - spyder
  - numpy
  - scipy
  - pandas
  - holoviews
  - bokeh
  - joblib
  - xarray
  - scikit-learn
  - seaborn
  - pytables
  - pip:
    - salib